### ISSUE TITLE
Strange behavior in PDB files selection, leading to a bug in haddock3

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock-runner#71]
### Bug Description

The automated selection of files using PDB keys did not behave as expected
In the case of target 1IRA, there is the presence of 1IRAtrunc also.

While input molecules were found, for ambig/target files, both 1IRA* 1IRAtrunc* were added.

This lead to a bug in haddock3

```
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.0 on 2023-09-24 03:10:00

Python 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0]

[2023-09-24 03:10:12,740 libutil ERROR] Something is wrong with the config file.
Traceback (most recent call last):
  File "/trinity/login/vreys/miniconda3/envs/haddock3/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/trinity/login/vreys/miniconda3/envs/haddock3/lib/python3.9/site-packages/toml/decoder.py", line 781, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trinity/login/vreys/haddock3/src/haddock/gear/config.py", line 220, in loads
    cfg_dict = toml.loads(cfg)  # Try to load it with the toml library
  File "/trinity/login/vreys/miniconda3/envs/haddock3/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 16 column 1 char 267)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/trinity/login/vreys/haddock3/src/haddock/gear/config.py", line 140, in load
    return loads(Path(fpath).read_text())
  File "/trinity/login/vreys/haddock3/src/haddock/gear/config.py", line 222, in loads
    raise ConfigurationError(
haddock.core.exceptions.ConfigurationError: Some thing is wrong with the config file: Duplicate keys! (line 16 column 1 char 267)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/trinity/login/vreys/haddock3/src/haddock/libs/libutil.py", line 310, in log_error_and_exit
    yield
  File "/trinity/login/vreys/haddock3/src/haddock/clis/cli.py", line 135, in main
    params, other_params = setup_run(
  File "/trinity/login/vreys/haddock3/src/haddock/gear/prepare_run.py", line 213, in setup_run
    config_files = read_config(workflow_path)
  File "/trinity/login/vreys/haddock3/src/haddock/gear/config.py", line 142, in load
    raise ConfigurationError('Something is wrong with the config file.') from err  # noqa: E501
haddock.core.exceptions.ConfigurationError: Something is wrong with the config file.
[2023-09-24 03:10:12,742 libutil ERROR] Something is wrong with the config file.
[2023-09-24 03:10:12,742 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-09-24 03:10:12,742 libutil INFO] Finished at 24/09/2023 03:10:12. For any help contact us at https://github.com/haddocking/haddock3/issues. Tot ziens! Adéu-siau! Agur!.
```

### Expected Behavior

When pdb is 1IRA, only 1IRA_* should be taken
When pdb is 1IRAtrunc, only 1IRAtrunc_* should be taken.

### Possible Solution

Add underscores at the end of search expression ?

## Steps to Reproduce

1. Run haddock-runner on BM5-dataset.

### Detailed Description

```toml
queue_limit = 100
concat = 5
postprocess = true
mode = "hpc"
queue = "short"
run_dir = "run1"
molecules = [
    "../data/1IRA_r_u.pdb",
    "../data/1IRA_l_u.pdb",
]

[topoaa]
autohis = true
[rigidbody]
ambig_fname = "../data/1IRAtrunc_threshold_0_3.tbl.tgz"
ambig_fname = "../data/1IRA_threshold_0_3.tbl.tgz"
tolerance = 3
[caprieval]
reference_fname = "../data/1IRAtrunc_target.pdb"
reference_fname = "../data/1IRA_target.pdb"
[clustfcc]
[seletopclusts]
top_models = 4
['caprieval.1']
reference_fname = "../data/1IRAtrunc_target.pdb"
reference_fname = "../data/1IRA_target.pdb"
[flexref]
previous_ambig = true
tolerance = 8
['caprieval.2']
reference_fname = "../data/1IRAtrunc_target.pdb"
reference_fname = "../data/1IRA_target.pdb"
[emref]
previous_ambig = true
tolerance = 5
['caprieval.3']
reference_fname = "../data/1IRAtrunc_target.pdb"
reference_fname = "../data/1IRA_target.pdb"
['clustfcc.2']
['seletopclusts.2']
top_models = 4
['caprieval.4']
reference_fname = "../data/1IRAtrunc_target.pdb"
reference_fname = "../data/1IRA_target.pdb"
```

**Comment by VGPReys** [comment]
Is it because an issue in my `.yaml` config file, that contain file extensions ?

```yaml
# Define general parameters
general:
  executable: /trinity/login/vreys/internships/erdem/hd-runner.sh
  max_concurrent: 4
  haddock_dir: /trinity/login/vreys/haddock3
  receptor_suffix: _r_u
  ligand_suffix: _l_u
  input_list: /trinity/login/vreys/internships/erdem/bm5-cport-a3d-haddock3-inputs.list
  work_dir: /trinity/login/vreys/internships/erdem/BM5-CPORT-ARCTIC3D

# Define list of scenarios
scenarios:
# Parameters for Senario at CPORT threshold 0.30
  - name: cport-threshold-0_3
    parameters:
      general:
        mode: hpc
        queue: short
        queue_limit: 100
        concat: 5
        postprocess: true

      modules:
        order: [topoaa, rigidbody, caprieval, clustfcc, seletopclusts, caprieval.1, flexref, caprieval.2, emref, caprieval.3, clustfcc.2, seletopclusts.2, caprieval.4]
        topoaa:
          autohis: true
        rigidbody:
          ambig_fname: _threshold_0_3.tbl.tgz
          tolerance: 3
          unambig_fname: _restraint-bodies.tbl
        caprieval:
          reference_fname: _target.pdb
        clustfcc:
        seletopclusts:
          top_models: 4
        caprieval.1:
          reference_fname: _target.pdb
        flexref:
          previous_ambig: true
          tolerance: 8
          unambig_fname: _restraint-bodies.tbl
        caprieval.2:
          reference_fname: _target.pdb
        emref:
          previous_ambig: true
          tolerance: 5
          unambig_fname: _restraint-bodies.tbl
        caprieval.3:
          reference_fname: _target.pdb
        clustfcc.2:
        seletopclusts.2:
          top_models: 4
        caprieval.4:
          reference_fname: _target.pdb
```

**Comment by rvhonorato** [comment]
Thanks for the description @VGPReys, could you provide the lines of `input_list` that contains `1IRA`?

**Comment by VGPReys** [comment]
`cat input_list | grep 1IRA`

```
internships/erdem/BM5-clean/HADDOCK-ready/1IRAtrunc/1IRAtrunc_r_u.pdb
internships/erdem/BM5-clean/HADDOCK-ready/1IRAtrunc/1IRAtrunc_l_u.pdb
internships/erdem/BM5-clean/HADDOCK-ready/1IRAtrunc/1IRAtrunc_target.pdb
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_3.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_4.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_5.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_6.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_7.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_8.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_85.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_9.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_95.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRAtrunc_threshold_0_99.tbl.tgz
internships/erdem/BM5-clean/HADDOCK-ready/1IRA/1IRA_r_u.pdb
internships/erdem/BM5-clean/HADDOCK-ready/1IRA/1IRA_l_u.pdb
internships/erdem/BM5-clean/HADDOCK-ready/1IRA/1IRA_target.pdb
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_3.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_4.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_5.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_6.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_7.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_8.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_85.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_9.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_95.tbl.tgz
internships/erdem/BM5-cport-tbls/1IRA_threshold_0_99.tbl.tgz
```

**Comment by rvhonorato** [comment]
The bug is coming from here:

https://github.com/haddocking/haddock-runner/blob/10636ebee8c401edcc6775a2425aed3e73582d61/dataset/dataset.go#L457-L465

Which will match `pdb="***/1IRAtrunc_target.pdb"` with `1IRA` with a simple `string.Contains`. The solution is to replace L460 to a regex match
